### ISSUE TITLE
Byte compiled version lacks symbols at run time

### ISSUE THREAD

**Issue by apteryks** [canatella/bitbake-el#14]
The following line is required otherwise the byte compiled version doesn't work as expected:
`(eval-when-compile (require 'cl-lib))`

The workaround was to M-x load-library RET cl-lib and reevaluate the buffer of bitbake-el's source file.

**Comment by canatella** [comment]
Hello, thanks for the report. I added the compile time require.

**Comment by apteryks** [comment]
Thanks for the prompt fix :-)
